# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_topic', '0003_topic_reindex_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='summary',
            field=models.CharField(default='abc', max_length=1000, verbose_name='summary'),
            preserve_default=False,
        ),
    ]
